version: "1"
rules:
  - base: master
    upstream: delefme:master
    mergeMethod: hardreset
  - base: topic-time-selection-improvements
    upstream: delefme:topic-time-selection-improvements
    mergeMethod: hardreset
